# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert a Numeric Matrix to a CarSimr List
#'
#' This function takes a numeric matrix intended to represent a grid of cars
#' and converts it using the CarSimr class into a list format with S3 class attributes.
#'
#' @param grid Numeric matrix representing a grid of cars.
#' @return A list representing the car simulation, with S3 class attributes.
#' @export
cpp_convert_carsimr <- function(grid) {
    .Call(`_carsimr_Thota_cpp_convert_carsimr`, grid)
}

#' Initialize a Grid with Cars
#'
#' This function creates a grid of the specified dimensions where each cell
#' may randomly contain a car based on the specified probability. The type
#' of car (blue or red) is also determined based on a probability.
#'
#' @param rho A numeric value that can either be a proportion of cells to fill
#' (between 0 and 1) or a total number of cars if greater than 1.
#' @param dims An integer vector specifying the dimensions of the grid (rows,
#' columns).
#' @param prob_blue A numeric probability (between 0 and 1) that a car will be
#' blue;
#' the probability of a car being red is 1 - prob_blue.
#'
#' @return A numeric matrix representing the grid, where 0 indicates an empty
#' cell, 1 indicates a blue car, and 2 indicates a red car.
#' @export
initialize_grid_cpp <- function(rho, dims, prob_blue) {
    .Call(`_carsimr_Thota_initialize_grid_cpp`, rho, dims, prob_blue)
}

#' Move Cars on a Grid
#'
#' This function simulates moving cars in a grid for a specified number of trials.
#' Cars move according to specific rules: red cars move right on even-numbered trials
#' and blue cars move up on odd-numbered trials.
#'
#' @param grid A numeric matrix representing the initial state of the grid,
#' where 0 indicates an empty cell, 1 indicates a blue car, and 2 indicates a red car.
#' @param trials An integer representing the number of movements to simulate.
#'
#' @return A numeric matrix representing the grid after all movements have been simulated.
#' @export
move_cars_cpp <- function(grid, trials) {
    .Call(`_carsimr_Thota_move_cars_cpp`, grid, trials)
}

